In [1]:
import numpy as np

In [2]:
ar1=np.arange(1,20,2)
print(ar1)

[ 1  3  5  7  9 11 13 15 17 19]


In [3]:
ar1-2

array([-1,  1,  3,  5,  7,  9, 11, 13, 15, 17])

In [5]:
ar1[3]

7

In [6]:
ar1[-2]

17

In [7]:
ar1[3:8]

array([ 7,  9, 11, 13, 15])

In [10]:
ar1[2:]

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
ar1[:8]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [13]:
ar1[-1:-6:-1]

array([19, 17, 15, 13, 11])

In [6]:
#2d array
import numpy as np
ar2=np.array([2,3,4,5,7,8,9,10]).reshape(2,4)
print(ar2)

[[ 2  3  4  5]
 [ 7  8  9 10]]


In [7]:
ar2[-2,-1]

5

In [10]:
ar2[:,1:3]

array([[3, 4],
       [8, 9]])

In [13]:
ar3=np.arange(15).reshape(3,5)
print(ar3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [14]:
ar3[:2,1:3]

array([[1, 2],
       [6, 7]])

In [16]:
ar3[-1:-3:-1,-3:-1]

array([[12, 13],
       [ 7,  8]])

In [17]:
ar3[:2,0:2]

array([[0, 1],
       [5, 6]])

In [18]:
ar4=np.arange(10).reshape(5,2)
print(ar4)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [19]:
res=ar3.dot(ar4)

In [20]:
print(res)

[[ 60  70]
 [160 195]
 [260 320]]


In [22]:
res.transpose()

array([[ 60, 160, 260],
       [ 70, 195, 320]])